# Setup
title:        Caddy file
tagline:      Caddy配置文件Caddyfile
baseurl:      "https://caddyfile.cf"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Caddy
  url:        https://caddyfile.cf
  
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
